export default function projectsJSON() {
  const projects = [
    {
      type: "gv",
      path: ["bsc1.jpeg", "bsc2.jpeg", "bsc3.jpeg", "bsc4.jpeg", "bsc5.jpeg", "bsc6.jpeg", "bsc7.jpeg", "bsc8.jpeg", "bsc10.jpeg", "bsc11.jpeg", "bsc12.jpeg", "bsc13.jpeg", "bsc15.jpeg", "bsc16.jpeg", "bsc17.jpeg", "bsc18.jpeg", "bsc19.jpeg", "bsc20.jpeg", "bsc21.jpeg", "bsc22.jpeg"],
      video: ["https://drive.google.com/file/d/1Q2MEhqjH-NOb3aMmhJZdDfZOof1a90UR/preview", "https://drive.google.com/file/d/1A_lYB-0Y3vIK1JPTNiEYt_pukShqI_31/preview"],
      title: "Batangas Sports Complex",
      description: "Various HENCHGAL products installed at Batangas Sports Complex in Batangas City.",
      fullDesc: "",
      products: [53026,45032, 80121],
      date: "",
      duration: "",
      location: "Batangas Sports Complex, Batangas City"
    },
    {
      type: "gv",
      path: ["infanta.jpg"],
      video: ["https://drive.google.com/file/d/14I4tYqM8bZuOVOa9WbUbCAzzFzVw3UX8/preview"],
      title: "Marikina-Infanta Highway",
      description: "Also known as MARILAQUE Highway.",
      fullDesc: "",
      products: [45032],
      date: "",
      duration: "",
      location: "Marikina-Infanta Hwy, Real, Quezon"
    },
    {
      type: "cs",
      path: ["ch1.png"],
      video: [],
      title: "Children's Hospital Project",
      description: "No description.",
      fullDesc: "",
      products: [35860],
      date: "",
      duration: "",
      location: ""
    },
    {
      type: "cs",
      path: ["elyu1.png", "elyu2.png", "elyu3.png", "elyu4.png", "elyu5.png", "elyu6.png"],
      video: [],
      title: "San Fernando, La Union Solar Lights",
      description: "Lighting up the city center with bright lights.",
      fullDesc: "",
      products: [53026, 45032],
      date: "",
      duration: "",
      location: "San Fernando, La Union"
    },
    {
      type: "cs",
      path: ["kh1.png", "kh2.png", "kh3.png", "kh4.png", "kh5.png", "kh6.png", "kh7.png", "kh8.png", "kh9.png","kh10.png"],
      video: [],
      title: "Kamay Ni Hesus Solar Lights",
      description: "LED-Lights installed inside Kamay Ni Hesus.",
      fullDesc: "",
      products: [34822],
      date: "",
      duration: "",
      location: "Kamay Ni Hesus, Lucban Quezon"
    },
    {
      type: "cs",
      path: ["tanza1.png", "tanza2.png", "tanza3.png", "tanza4.png", "tanza5.png", "tanza6.png", "tanza7.png", "tanza8.png", "tanza9.png","tanza10.png", "tanza11.png"],
      video: [],
      title: "Tanza, Cavite Solar Road Lights",
      description: "LED-Lights installed at various locations in Tanza.",
      fullDesc: "",
      products: [53026, 45032],
      date: "",
      duration: "",
      location: "Tanza, Cavite"
    },
    {
      type: "gv",
      path: ["soccoro.jpg"],
      video: [],
      title: "Municipality of Socorro, Oriental Mindoro",
      description:
        "UFO Solar Street Light installed at Boardwalk—Naujan Lake National Park",
        fullDesc: "",
        products: [80121],
      date: "",
      duration: "",
      location: "Socorro, Oriental Mindoro"
    },
    {
      type: "gv",
      path: ["gso.jpg"],
      title: "Provincial Government of Batangas—GSO",
      video: [],
      description:
        "UFO Solar Street Light installed at Capitol Compound, Kumintang Ibaba, Batangas City",
        fullDesc: "",
        products: [80121],
      date: "",
      duration: "",
      location: "Kumintang Ibaba, Batangas City"
    },
    {
      type: "gv",
      path: ["soccoro2.jpg"],
      video: [],
      title: "Municipal Building of Socorro, Oriental Mindoro",
      description: "LED High bay installed at the municipal gymnasium",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Socorro, Oriental Mindoro"
    },
    {
      type: "gv",
      path: ["bacoor.png"],
      video: [],
      title: "City Government of Bacoor",
      description:
        "Cavite LED UFO High bay lights installed at Strike Gymnasium",
        fullDesc: "",
        products: [],
      date: "",
      duration: "",
      location: "Bacoor, Cavite"
    },
    {
      type: "gv",
      path: ["tk.png"],
      title: "Municipality of Tagkawayan, Quezon",
      description: "LED High bay lights installed at the municipal gymnasium",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Tagkawayan, Quezon",
    video: [],
    },
    {
      type: "gv",
      path: ["romblon.png"],
      title: "Municipality of Corcuera, Romblon",
      description:
        "LED UFO High bay lights installed at the municipal covered court.",
        fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Corcuera, Romblon",
    video: [],
    },
    {
      type: "hsp",
      path: ["lmc.jpg"],
      title: "Luzon Medical Center",
      description: "LED lights installed at hospital rooms.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Luzon Medical Center",
    video: [],
    },
    {
      type: "hsp",
      path: ["mamc.jpg"],
      title: "Adventist Medical Center Manila",
      description:
        "LED Tubes and panel installed at hospital rooms and at the new parking.",
        fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Adventist Medical Center Manila",
    video: [],
    },
    {
      type: "hsp",
      path: ["pah.jpg"],
      title: "Palawan Adventist Hospital",
      description: "LED lights installed at hospital rooms.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Palawan Adventist Hospital",
    video: [],
    },
    {
      type: "sch",
      path: ["AIAS.png"],
      title: "Adventist International Institute of Advanced Studies",
      description: "LED Top-pots and street lights installed.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Adventist International Institute of Advanced Studies",
    video: [],
    },
    {
      type: "sch",
      path: ["aup.jpg"],
      title: "Adventist University of the Philippines",
      description: "LED Top-post installed at student eco-park.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Adventist University of the Philippines",
    video: [],
    },
    {
      type: "sch",
      path: ["lipa adventist academy.jpg"],
      title: "Lipa Adventist Academy",
      description:
        "LED Tubes installed at classrooms, high bay at the school gymnasium.",
        fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Lipa Adventist Academy",
    video: [],
    },
    {
      type: "sch",
      path: ["baesa.png"],
      title: "Baesa Adventist Academy- Baesa, Caloocan City",
      description: "LED lighting installed at classrooms.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Baesa, Caloocan City",
    video: [],
    },
    {
      type: "sch",
      path: ["baesaaap.png"],
      title: "Baesa Adventist Academy- Baesa, Caloocan City",
      description: "LED lighting installed at classrooms.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Baesa, Caloocan City",
    video: [],
    },
    {
      type: "sch",
      path: ["marin.png"],
      title: "Marinduque State College",
      description: "LED lighting installed at classrooms.",
      fullDesc: "",
      products: [],
    date: "",
    duration: "",
    location: "Marinduque State College",
    video: [],
    },
  ];
    return  projects;
}
